### ISSUE TITLE
doesn't work on vivaldi

### ISSUE THREAD

**Issue by starnakin** [Mallow-x/BetterVoirAnime#1]
sorry I like this project but I can't use them on vivaldi: I have a page without any content
![image](https://user-images.githubusercontent.com/47717174/191544335-09ffa420-93c4-4d92-a630-fb8a2c86ff97.png)

**Comment by Mallow-x** [comment]
Hello starnakin, thanks for using my extension, could you give me mp me on discord to talk about the problems ? It will be much easier to do it on discord. **Mallow#5569**
